import { Router } from "express";
import ExpenseController from "../controllers/expense.controller";
import authMiddleware from "../middlewares/auth.middleware";
import validate from "../middlewares/validate.js";
import { createExpenseSchema, updateExpenseSchema, settlementSchema } from "../validator/expense.validator.js";
const router = Router();
router.post("/", authMiddleware, validate(createExpenseSchema), ExpenseController.createExpense);
router.get("/", authMiddleware, ExpenseController.getExpenses);
router.post("/settlements", authMiddleware, validate(settlementSchema), ExpenseController.ExpenseSettle);
router.put("/:id", authMiddleware, validate(updateExpenseSchema), ExpenseController.updateExpense);
router.delete("/:id", authMiddleware, ExpenseController.deleteExpense);
export default router;
